version: "3"
services:
  api:
    image: kingholyhill/fastapi
    depends_on:
      - postgres
    ports: 
      - 80:8000
    # env_file:
    #   - ./.env.docker
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRY=${ACCESS_TOKEN_EXPIRY}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
  postgres:
    image: postgres
    # env_file: 
    #   - ./.env.docker.postgres
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
