name: Build and Deploy Code

on: 
  push: 
    branches:
      - "main"
  pull_request: 
    branches:
      - "dev"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi
        run: echo "hello kingsley"