name: Build and Deploy Code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job1:
    environment: 
      name: testing
    env:
      DB_HOST: ${{secrets.DB_HOST}}
      DB_PORT: ${{secrets.DB_PORT}}
      DB_NAME: ${{secrets.DB_NAME}}
      DB_USER: ${{secrets.DB_USER}}
      DB_PASS: ${{secrets.DB_PASS}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRY: ${{secrets.ACCESS_TOKEN_EXPIRY}}

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env: 
          POSTGRES_HOST: ${{secrets.DB_HOST}}
          POSTGRES_PASSWORD: ${{secrets.DB_PASS}}
          POSTGRES_DB: ${{secrets.DB_NAME}}_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # - name: Install PostgreSQL client
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install --yes postgresql-client

      # # queries database with postgres client
      # - name: Query database
      #   run: psql -h localhost -d fast_api_test -U postgres -c 'SELECT 1;'
      #   env:
      #     # postgress password is required; alternatively, you can run:
      #     # `PGPASSWORD=postgres_password psql ...`
      #     PGPASSWORD: ${{secrets.DB_PASS}}
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: install python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: update pip
        run: python -m pip install --upgrade pip
      - name: install all dependencies
        run: pip install -r requirements.txt
      - name: test with pytest
        run: |
          pip install pytest
          pytest tests/test_3_likes.py -v -s 
          